
filetype plugin indent on

syntax on

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set title
set hlsearch
set ignorecase smartcase
set ruler
set number
set lazyredraw
set background=light
" Autoreloads modfied file.
set autoread

imap jk <Esc>

" Disable arrow keys in insert mode. Live a better life.
imap <Left> <NOP>
imap <Right> <NOP>
imap <Up> <NOP>
imap <Down> <NOP>
map § ~


" Proper permissions for the file.
noremap <F4> :w<cr>:! chmod 700 %<cr><cr>
" Write and run the script in Vim's shell.
noremap <F5> :w<cr>:!%:p<cr>

" Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm

set noswapfile
set backup
set backupdir=~/.vimbak

