
filetype plugin indent on

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set title
set hlsearch
set ignorecase smartcase
set ruler
set lazyredraw
set background=light

syntax on

" Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm

inoremap jk <Esc>
inoremap kj <Esc>

set backup
set backupdir=~/.vimbak
set directory=~/.vimbak
